axelarnetwork/interchain-token-service

contracts/interchainTokenService/InterchainTokenService.sol, contracts/interfaces/IExpressCallHandler.sol, contracts/interfaces/IInterchainTokenService.sol, contracts/utils/ExpressCallHandler.sol
Added flow limits that only trigger if abs(flowIn - flowOut) > flowLimit and added tests.
=> feat: express call

package-lock.json, package.json
Updating CGP and GMP-SDK dependencies
=> chore: dependencies upgrade

contracts/interchain-token-service/InterchainTokenService.sol, contracts/interchain-token/InterchainToken.sol, contracts/interfaces/IInterchainToken.sol, contracts/interfaces/IInterchainTokenExecutable.sol, contracts/interfaces/IInterchainTokenExpressExecutable.sol, contracts/interfaces/IInterchainTokenService.sol, contracts/interfaces/IRemoteAddressValidator.sol, contracts/interfaces/ITokenManager.sol, contracts/proxies/TokenManagerProxy.sol, contracts/test/utils/NakedProxy.sol, contracts/token-manager/TokenManager.sol, contracts/token-manager/implementations/TokenManagerAddressStorage.sol, contracts/utils/Distributable.sol, contracts/utils/FlowLimit.sol, docs/index.md
=> fix: typos

contracts/interchain-token-service/InterchainTokenService.sol
[AXE-1967]
[AXE-1967]: https://axelarnetwork.atlassian.net/browse/AXE-1967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: pass commandId explicitly

contracts/proxies/InterchainTokenServiceProxy.sol
[AXE-2448]
[AXE-2448]: https://axelarnetwork.atlassian.net/browse/AXE-2448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: use normal proxy for ITS

contracts/interchain-token-service/InterchainTokenService.sol, contracts/interfaces/IInterchainTokenService.sol, contracts/interfaces/IStandardizedTokenRegistrar.sol, contracts/token-registrars/CanonicalTokenRegistrar.sol, contracts/token-registrars/StandardizedTokenRegistrar.sol, docs/index.md, test/TokenRegistrars.js, test/TokenService.js, test/TokenServiceFullFlow.js
[AXE-2472](https://axelarnetwork.atlassian.net/browse/AXE-2472)
[AXE-2472]: https://axelarnetwork.atlassian.net/browse/AXE-2472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: renamed a bunch of stuff for simplifying (on another PR)

contracts/interfaces/ITokenManagerProxy.sol, contracts/proxies/InterchainTokenFactoryProxy.sol, contracts/proxies/InterchainTokenProxy.sol, contracts/proxies/InterchainTokenServiceProxy.sol, contracts/proxies/TokenManagerProxy.sol
NatSpec documentation for ITS proxy contracts as per [AXE-2436](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-2436)
[AXE-2436]: https://axelarnetwork.atlassian.net/browse/AXE-2436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: proxy natspec

contracts/InterchainTokenService.sol, contracts/interfaces/ITokenManager.sol, contracts/test/TestERC20.sol, contracts/test/TestFeeOnTransferToken.sol, contracts/test/TestFeeOnTransferTokenInvalid.sol, contracts/test/TestFeeOnTransferTokenNoFee.sol, contracts/token-manager/TokenManager.sol, test/ERC20.js, test/InterchainToken.js, test/TokenManager.js, test/TokenService.js
PR to remove any remaining ITS test coverage gaps from recent refactors as per [AXE-2620](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-2620)
[AXE-2620]: https://axelarnetwork.atlassian.net/browse/AXE-2620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: remove test coverage gaps

contracts/InterchainTokenService.sol, contracts/interfaces/IInterchainTokenService.sol, test/InterchainTokenFactory.js, test/TokenService.js, test/TokenServiceFullFlow.js
[AXE-2639]
[AXE-2639]: https://axelarnetwork.atlassian.net/browse/AXE-2639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(ITS protocol): unifying interchain transfer payload type

hardhat.config.js
[AXE-2689]
[AXE-2689]: https://axelarnetwork.atlassian.net/browse/AXE-2689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add compiler overrides for Proxy contracts

contracts/InterchainTokenFactory.sol, contracts/interchain-token/InterchainToken.sol, contracts/interfaces/ITokenManager.sol, contracts/token-manager/TokenManager.sol, test/InterchainTokenFactory.js, test/TokenService.js
[AXE-2731]
[AXE-2731]: https://axelarnetwork.atlassian.net/browse/AXE-2731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: set address(0) as operator/distributor by default

contracts/InterchainTokenService.sol, contracts/TokenHandler.sol, test/TokenService.js
Refactor lock unlock fee specific code in ITS using token handler
=> refactor: clean up token specific express handling

contracts/InterchainTokenService.sol, contracts/executable/InterchainTokenExecutable.sol, contracts/executable/InterchainTokenExpressExecutable.sol, contracts/interfaces/IInterchainTokenExecutable.sol, contracts/interfaces/IInterchainTokenExpressExecutable.sol, contracts/test/TestInterchainExecutable.sol, contracts/test/TestInvalidInterchainExecutable.sol, docs/index.md, test/TokenService.js
[AXE-2748]
[AXE-2748]: https://axelarnetwork.atlassian.net/browse/AXE-2748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add commandId to executables

contracts/InterchainTokenFactory.sol, contracts/token-manager/TokenManager.sol, test/InterchainTokenFactory.js, test/TokenManager.js, test/TokenServiceFullFlow.js
=> test: preserve 0 flow limiter and update full flow test

contracts/InterchainTokenService.sol, contracts/proxies/InterchainProxy.sol, contracts/proxies/Proxy.sol, scripts/deploy.js, test/InterchainTokenService.js
Add `InterchainProxy` to enable contract verification
=> feat: add interchain proxy

contracts/InterchainTokenFactory.sol, contracts/interfaces/IInterchainTokenFactory.sol, test/InterchainTokenFactory.js, test/InterchainTokenServiceFullFlow.js
[AXE-2766]
[AXE-2766]: https://axelarnetwork.atlassian.net/browse/AXE-2766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(Factory): removing token transfer functions

contracts/InterchainTokenService.sol, contracts/interfaces/IInterchainTokenService.sol, contracts/test/TestInterchainToken.sol, contracts/test/TestInterchainTokenService.sol, test/InterchainToken.js, test/InterchainTokenFactory.js, test/InterchainTokenService.js
Filling test coverage gaps after recent refactors as per [AXE-2761](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-2761)
[AXE-2761]: https://axelarnetwork.atlassian.net/browse/AXE-2761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: post refactor test coverage

scripts/deploy.js, test/AddressDerivation.js, test/utils.js
PR to test token address derivations for ITS and InterchainTokenFactory deploy methods as per [AXE-2729](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-2729)
[AXE-2729]: https://axelarnetwork.atlassian.net/browse/AXE-2729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: token address derivation test

scripts/deploy.js, test/AddressDerivation.js, test/ERC20Permit.js, test/InterchainTokenFactory.js, test/InterchainTokenService.js, test/InterchainTokenServiceFullFlow.js, test/InterchainTokenServiceUpgradeFlow.js, test/TokenManager.js, test/utils.js
Testing improvements for live testnets as per [AXE-2831](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-2831)
[AXE-2831]: https://axelarnetwork.atlassian.net/browse/AXE-2831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: live testnet improvements

.github/workflows/publish-bytecode.yaml, package-lock.json, package.json, scripts/flatten-contracts.sh
- Mimic bytecode publish action from cgp-solidity repo
- Port changes to the flatten script
- Bump release
=> ci: fix bytecode publish action

contracts/InterchainTokenFactory.sol, contracts/interfaces/IInterchainTokenFactory.sol, contracts/interfaces/IInterchainTokenService.sol, docs/index.md, package-lock.json, package.json
=> fix: add missing imports to factory interface (#240)

.github/workflows/publish-bytecode.yaml
=> ci: backport ci fixes

test/InterchainTokenFactory.js, test/InterchainTokenService.js
Additional test coverage post gateway token support as per [AXE-3026](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-3026)
[AXE-3026]: https://axelarnetwork.atlassian.net/browse/AXE-3026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: additional test coverage

.github/workflows/slither.yaml, hardhat.config.js
=> ci(slither): pinning the version

package-lock.json, package.json
https://axelarnetwork.atlassian.net/browse/AXE-3546
=> refactor: update axelar chains config version

.github/workflows/codecov.yaml, .github/workflows/test.yaml, contracts/InterchainTokenService.sol, contracts/interfaces/IInterchainTokenService.sol, contracts/types/InterchainTokenServiceTypes.sol, hardhat.config.js, test/InterchainTokenServiceFullFlow.js, test/utils.js
=> feat(its-hub): support its hub routing

DESIGN.md, README.md, contracts/InterchainTokenService.sol, contracts/interfaces/IGatewayCaller.sol, contracts/utils/GatewayCaller.sol
[AXE-4613]
[AXE-4613]: https://axelarnetwork.atlassian.net/browse/AXE-4613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(its)!: add more checks for its hub routing

contracts/InterchainTokenService.sol, contracts/utils/InterchainTokenDeployer.sol
[AXE-5205](https://axelarnetwork.atlassian.net/browse/AXE-5205)
- Use the named return variables for efficient gas and consistency.
[AXE-5205]: https://axelarnetwork.atlassian.net/browse/AXE-5205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: use named return

contracts/TokenHandler.sol
[AXE-6329](https://axelarnetwork.atlassian.net/browse/AXE-6329)
[AXE-6329]: https://axelarnetwork.atlassian.net/browse/AXE-6329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: eliminate redundant assignment

.github/workflows/slither.yaml, contracts/InterchainTokenFactory.sol, contracts/interfaces/IInterchainTokenFactory.sol, test/InterchainTokenFactory.js
[AXE-6319]
[AXE-6319]: https://axelarnetwork.atlassian.net/browse/AXE-6319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(its-factory)!: support arbitrary destination minter for remote deployment

package-lock.json, package.json
The release PR will bump it to v2 correctly
=> fix: revert package version to use the new release process

test/InterchainTokenFactory.js, test/InterchainTokenService.js, test/InterchainTokenServiceFullFlow.js
[AXE-7088]
[AXE-7088]: https://axelarnetwork.atlassian.net/browse/AXE-7088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: factory link token coverage

.changeset/grumpy-pets-turn.md, contracts/InterchainTokenService.sol, contracts/interfaces/IInterchainTokenService.sol, test/InterchainTokenService.js
[AXE-7081]
[AXE-7081]: https://axelarnetwork.atlassian.net/browse/AXE-7081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(its)!: remove callContractWithInterchainToken from ITS

contracts/InterchainTokenFactory.sol, contracts/InterchainTokenService.sol, contracts/interfaces/IInterchainTokenService.sol, scripts/deploy.js, test/AddressDerivation.js, test/InterchainTokenFactory.js, test/InterchainTokenService.js, test/InterchainTokenServiceFullFlow.js, test/InterchainTokenServiceUpgradeFlow.js
Also remove the ability to deploy custom token managers and interchain tokens for non-factory users.
[AXE-7090]
[AXE-7090]: https://axelarnetwork.atlassian.net/browse/AXE-7090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(its): add a registerCustomToken function in ITS and add support for it in factory

.changeset/sour-cheetahs-drop.md, contracts/InterchainTokenFactory.sol, contracts/interfaces/IInterchainTokenFactory.sol, test/InterchainTokenFactory.js, test/InterchainTokenServiceFullFlow.js
[AXE-7170]
[AXE-7170]: https://axelarnetwork.atlassian.net/browse/AXE-7170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(its-factory): remove minter from deployRemoteInterchainToken

.changeset/metal-dogs-carry.md, contracts/InterchainTokenFactory.sol, contracts/interfaces/IInterchainTokenFactory.sol, test/InterchainTokenFactory.js, test/InterchainTokenServiceFullFlow.js, test/InterchainTokenServiceUpgradeFlow.js
[AXE-7225]
[AXE-7225]: https://axelarnetwork.atlassian.net/browse/AXE-7225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(its-factory)!: remove auto-registration of token metadata

contracts/InterchainTokenService.sol, contracts/interfaces/IGatewayCaller.sol, contracts/utils/GatewayCaller.sol, test/InterchainTokenService.js
[AXE-8399](https://axelarnetwork.atlassian.net/browse/AXE-8399)
[AXE-8399]: https://axelarnetwork.atlassian.net/browse/AXE-8399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(its): remove express call metadata version

contracts/InterchainTokenService.sol, contracts/interfaces/IInterchainTokenService.sol, test/InterchainTokenService.js
[AXE-9050](https://axelarnetwork.atlassian.net/browse/AXE-9050)
[AXE-9050]: https://axelarnetwork.atlassian.net/browse/AXE-9050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(its): re-introduce callContractWithInterchainToken

.changeset/metal-lamps-pull.md, contracts/InterchainTokenService.sol, contracts/interfaces/IGatewayCaller.sol, contracts/test/TestInterchainTokenService.sol, contracts/utils/GatewayCaller.sol
[AXE-9108](https://axelarnetwork.atlassian.net/browse/AXE-9108)
[AXE-9108]: https://axelarnetwork.atlassian.net/browse/AXE-9108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(its): remove metadata version
