.solcover.js
hardhat.config.js

Generate unit test coverage report via:
`COVERAGE=true npx hardhat coverage`
To view the report
`open ./coverage/index.html`
For coverage to work correctly, some optimizations need to skipped

feat: solidity unit test coverage

---

package.json

This lets package managers like NPM link back to this repository.

chore: add repository link

---

contracts/interchain-token-service/InterchainTokenService.sol
contracts/interfaces/ITokenManagerType.sol
contracts/token-manager/implementations/TokenManagerLiquidityPool.sol
scripts/deploy.js
test/TokenService.js

PR to remove the liquidity pool token manager implementation type from `InterchainTokenService` as per [AXE-2063](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-2063)
[AXE-2063]: https://axelarnetwork.atlassian.net/browse/AXE-2063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: remove liquidity pool token manager from ITS

---

contracts/test/utils/FlowLimitTestLiveNetwork.sol
test/UtilsTest.js
test/utils.js

Proposed fix for time dependent flow limit tests as per [AXE-2171](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-2171)
[AXE-2171]: https://axelarnetwork.atlassian.net/browse/AXE-2171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: flowLimit tests live network support

---

contracts/interchain-token/BaseInterchainToken.sol
contracts/interchain-token/InterchainToken.sol
contracts/interfaces/IInterchainToken.sol
contracts/interfaces/IInterchainTokenStandard.sol
contracts/test/FeeOnTransferTokenTest.sol
contracts/test/InterchainTokenTest.sol
contracts/test/InvalidInterchainToken.sol
docs/index.md

Use `IInterchainTokenStandard` naming convention

refactor: rename token standard interface

---

test/TokenService.js

Small PR to remove unnecessary unpause transactions from `beforeEach` blocks

fix: remove unpause txs

---

contracts/interfaces/IFlowLimit.sol
contracts/test/utils/TestFlowLimitLiveNetwork.sol
contracts/utils/FlowLimit.sol
docs/index.md
test/TokenService.js
test/UtilsTest.js

Adding token manager address as an argument for `flowLimitExceeded` error because this information is needed in monitoring scripts. Connected to [AXE-2705](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-2705)
[AXE-2705]: https://axelarnetwork.atlassian.net/browse/AXE-2705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: flow limit exceeded error

---

contracts/InterchainTokenService.sol
hardhat.config.js
test/TokenManager.js
test/TokenService.js

fix(ITS): token type LOCK_UNLOCK_FEE express amount

---

contracts/InterchainTokenFactory.sol
contracts/interfaces/IInterchainTokenFactory.sol

fix(Factory): tracking deployer balance

---

contracts/InterchainTokenService.sol
test/InterchainTokenService.js

fix: check token sender earlier

---

contracts/interchain-token/ERC20.sol
contracts/token-manager/TokenManager.sol

The uint256 max constant can be set using `type(uint256).max`
Resolves #222

refactor: set max uint256 value dynamically

---

.github/workflows/codecov.yaml
.github/workflows/conventional-commits.yaml
.github/workflows/lint.yaml
.github/workflows/slither.yaml
.github/workflows/test.yaml

Integrate codecov as per [AXE-3415](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-3415)
[AXE-3415]: https://axelarnetwork.atlassian.net/browse/AXE-3415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add codecov action

---

contracts/InterchainTokenFactory.sol
contracts/InterchainTokenService.sol
test/InterchainToken.js

fix(factory): remove unused using directives

---

.github/workflows/codecov.yaml
.github/workflows/conventional-commits.yaml
.github/workflows/coverage.yaml
.github/workflows/lint.yaml
.github/workflows/slither.yaml
.github/workflows/test.yaml
package-lock.json
package.json

Switch to blacksmith for GitHub actions

feat: add blacksmith

---

contracts/InterchainTokenService.sol
contracts/TokenHandler.sol
contracts/interfaces/IInterchainTokenService.sol
contracts/interfaces/ITokenHandler.sol
test/InterchainTokenService.js

https://axelarnetwork.atlassian.net/browse/AXE-3594

feat: move more to token handler

---

.github/workflows/codecov.yaml
.github/workflows/test.yaml
contracts/InterchainTokenFactory.sol
contracts/InterchainTokenService.sol
contracts/TokenHandler.sol
contracts/interfaces/IInterchainTokenFactory.sol
hardhat.config.js
package-lock.json
package.json
test/InterchainTokenFactory.js

[AXE-4614]
[AXE-4614]: https://axelarnetwork.atlassian.net/browse/AXE-4614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix!: prefix gateway token salt derivation

---

README.md

- `COVERAGE=true npm run test` command fails to generate coverage report with errors.
- `npm run coverage` gives the coverage report successfully without errors.

docs: readme updates for coverage command

---

contracts/InterchainTokenFactory.sol
contracts/InterchainTokenService.sol
contracts/interfaces/IInterchainTokenFactory.sol
contracts/interfaces/ITokenManagerType.sol

[AXE-4727](https://axelarnetwork.atlassian.net/browse/AXE-4727) : incorrect comments update
[AXE-4727]: https://axelarnetwork.atlassian.net/browse/AXE-4727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: incorrect comments updates

---

contracts/InterchainTokenService.sol

[AXE-4792](https://axelarnetwork.atlassian.net/browse/AXE-4792)
- Modified [L-01] Wrong data decoding in _checkPayloadAgainstGatewayData
- Unit test coverage remains the same
[AXE-4792]: https://axelarnetwork.atlassian.net/browse/AXE-4792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: modified wrong data decoding in _checkPayloadAgainstGatewayData

---

contracts/InterchainTokenService.sol
test/constants.js

Devnet amplifier ITS hub instance uses `axelarnet` as the chain name (via the axelarnet-gateway)
[AXE-5292]
[AXE-5292]: https://axelarnetwork.atlassian.net/browse/AXE-5292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix!: use lower case ITS hub chain name

---

contracts/InterchainTokenService.sol
test/InterchainTokenService.js

[AXE-5210](https://axelarnetwork.atlassian.net/browse/AXE-5210)
- added `InterchainTokenIdClaimed` event
- `coverage` remains the same. 
[AXE-5210]: https://axelarnetwork.atlassian.net/browse/AXE-5210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: added InterchainTokenIdClaimed event

---

contracts/InterchainTokenFactory.sol
contracts/InterchainTokenService.sol
contracts/interfaces/IInterchainTokenFactory.sol
contracts/interfaces/IInterchainTokenService.sol
hardhat.config.js
test/InterchainTokenFactory.js
test/InterchainTokenService.js
test/InterchainTokenServiceFullFlow.js

[AXE-4776](https://axelarnetwork.atlassian.net/browse/AXE-4776)
- In `InterchainTokenFactory.deployRemoteInterchainToken`, check if `destinationChain` is the same as `originalChainName` to prevent remote deployment requests to the original chain.
- Check originalChainName and destinationChain in `InterchainTokenFactory.deployRemoteCanonicalInterchainToken` to ensure that a remote deploy cannot be requested to the original chain.
- Unit test coverage is 100% for `InterchainTokenFactory.sol` and `InterchainTokenService.sol`
```
----------------------------------------|----------|----------|----------|----------|----------------|
File                                    |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------------------------------|----------|---------- …
```

fix: preventing original chain name & destination chain name are the same

---

contracts/InterchainTokenFactory.sol
test/InterchainTokenFactory.js

[AXE-5581](https://axelarnetwork.atlassian.net/browse/AXE-5581)
- Remove gateway token check for registerCanonicalInterchainToken in Interchain Token Factory
- Coverage remains 100%:
```
----------------------------------------|----------|----------|----------|----------|----------------|
File                                    |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------------------------------|----------|----------|----------|----------|----------------|
InterchainTokenFactory.sol            |      100 |      100 |      100 |      100 |                |
```
[AXE-5581]: https://axelarnetwork.atlassian.net/browse/AXE-5581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(its): remove gateway token check for registerCanonicalInterchainToken

---

contracts/InterchainTokenService.sol
test/constants.js

[AXE-6054]
[AXE-6054]: https://axelarnetwork.atlassian.net/browse/AXE-6054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix!: update its hub chain name

---

contracts/InterchainTokenService.sol
contracts/interfaces/IInterchainTokenService.sol
package-lock.json
package.json
test/InterchainTokenService.js

[AXE-6277]
Reduces bytecode size by ~800 bytes
[AXE-6277]: https://axelarnetwork.atlassian.net/browse/AXE-6277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(its)!: remove gateway token entrypoints

---

.changeset/config.json
package.json

- Set the package's publish visibility to `public`.

ci: set package publish visibility to public

---

contracts/InterchainTokenFactory.sol
contracts/InterchainTokenService.sol
contracts/interfaces/IInterchainTokenService.sol
docs/index.md
test/InterchainTokenService.js
test/InterchainTokenServiceFullFlow.js

[AXE-6093](https://axelarnetwork.atlassian.net/browse/AXE-6093)
- `validTokenManagerAddress` renamed to `deployedTokenManager`: Clearly indicates this function retrieves the address of a deployed TokenManager.
- `validTokenAddress` renamed to `registeredTokenAddress`: Indicates it returns the token address managed by an already deployed `TokenManager`.
[AXE-6093]: https://axelarnetwork.atlassian.net/browse/AXE-6093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(its): rename valid token methods to more reeadable

---

contracts/interfaces/IFlowLimit.sol
contracts/utils/FlowLimit.sol
test/InterchainTokenService.js

[AXE-4786](https://axelarnetwork.atlassian.net/browse/AXE-4786)
[AXE-4786]: https://axelarnetwork.atlassian.net/browse/AXE-4786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(flow-limit): handle large flow limit values

---

contracts/InterchainTokenService.sol
contracts/interfaces/IInterchainTokenService.sol
test/InterchainTokenService.js

[AXE-6320](https://axelarnetwork.atlassian.net/browse/AXE-6320)
[AXE-6320]: https://axelarnetwork.atlassian.net/browse/AXE-6320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(its): add validation checks for evm its message fields

---

.github/workflows/codecov.yaml
contracts/InterchainTokenFactory.sol
contracts/interfaces/IInterchainTokenFactory.sol
docs/index.md
scripts/flatten-contracts.sh
test/InterchainTokenFactory.js

[AXE-6588]
[AXE-6588]: https://axelarnetwork.atlassian.net/browse/AXE-6588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(its-factory)!: simplify token id derivation

---

test/AddressDerivation.js
test/InterchainTokenFactory.js
test/InterchainTokenService.js
test/InterchainTokenServiceFullFlow.js
test/utils.js

[AXE-9171](https://axelarnetwork.atlassian.net/browse/AXE-9171)
[AXE-9171]: https://axelarnetwork.atlassian.net/browse/AXE-9171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: use its message encoding for tests
